TITLE_CORRECTIONS = {
                                                                    '3 dÌas': 'Tres días',
                                                                    'AmÈlie': 'Amélie',
                                                                   'AÒo uÒa': 'Año uña',
                                                                  'RashÙmon': '羅生門',
                                                                 '11í09íí01': '''11'09"01 September 11''',
                                                                 'Ant·rtida': 'Antártida',
                                                                '7 VÌrgenes': '7 vírgenes',
                                                               'AÒo Mariano': 'Año Mariano',
                                                               'Dj˙pi\uf8ff': 'Djúpið',
                                                              'A LíAttaque!': "À l'attaque!",
                                                              'Fucking AmÂl': 'Fucking Åmål',
                                                             'A puerta frÌa': 'A puerta fría',
                                                            '20 CentÌmetros': '20 centímetros',
                                                            'Acción mutante': 'Acción mutante',
                                                           'Ali G InDaHouse': 'Ali G Indahouse',
                                                           'Apaga y v·monos': 'Apaga y vámonos',
                                                          'AimÈe and Jaguar': 'Aimée & Jaguar',
                                                          'At˙n y chocolate': 'Atún y chocolate',
                                                         'Arr·ncame la vida': 'Arráncame la vida',
                                                        'A Hard Dayís Night': "A Hard Day's Night",
                                                        'Preview/ Pelo malo': 'Pelo malo',
                                                       'Preview/ La Partida': 'La Partida',
                                                     'Aunque t˙ no lo sepas': 'Aunque tú no lo sepas',
                                                    'All Tomorrowís Parties': "All Tomorrow's Parties",
                                                 'A Boy Called Dad/ Preview': 'A Boy Called Dad',
                                                 'A Midsummerís Night Dream': "A Midsummer's Night Dream",
                                                 'Plan B/ Preview Screening': 'Plan B',
                                                'Gigante/ Preview Screening': 'Gigante',
                                                '°Viva la nueva generaciÛn!': '¡Viva la nueva generación!',
                                               "The Best of Ji&#345;Ì Trnka": 'The Best of Jiří Trnka',
                                              'Aurora boreal: Mi ˙ltimo dÌa': 'Aurora Boreal',
                                             'Awesome; I F**kiní Shot That!': "Awesome; I Fuckin' Shot That!",
                                            'ävankmajer & The Brothers Quay': 'The Cabinet of Jan Svankmajer & The Brothers Quay',
                                           'Epizoda u éivotu Bera a éeljeza': 'Epizoda u životu berača željeza',
                                         'Los Años Desnudos: Clasificada ëS': 'Los años desnudos (Clasificada S)',
                                        'The Lodger plus Live Accompaniment': 'The Lodger: A Story of the London Fog',
                                       'La teta asustada/ Preview Screening': 'La teta asustada',
                                     '24 cines por segundo: S·banas blancas': '24 cines por segundo: Sábanas blancas',
                                     'Special UK Preview: Premier/Divisions': 'Divisions',
                            'A Twisted Nerve Tip : Four Flies on Grey Velve': '4 mosche di velluto grigio',
              'Preview/ Northern Soul - part of the 6 Music Festival Fringe': 'Northern Soul - part of the 6 Music Festival Fringe',
"A Liar's Autobiography ñ The Untrue Story of Monty Pythonís Graham Chapman": "A Liar's Autobiography: The Untrue Story of Monty Python's Graham Chapman",
}

# vim: set colorcolumn=0:
